services:
  - type: web
    name: bror50-game
    env: python
    buildCommand: echo "No build step needed"
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
    plan: free 